# Cloud Build — Image build only (triggered by Cloud Build trigger or manually).
# Deployment is handled by GitHub Actions + Pulumi.
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/photogrammetry/api:$COMMIT_SHA"
      - "./api"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/photogrammetry/api:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/photogrammetry/worker:$COMMIT_SHA"
      - "./worker"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/photogrammetry/worker:$COMMIT_SHA"

images:
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/photogrammetry/api:$COMMIT_SHA"
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/photogrammetry/worker:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"
