config:
  gcp:project: cl-operational
  gcp:region: southamerica-east1
  photogrammetry-service:environment: dev
  photogrammetry-service:allowedOrigins: "*"
  photogrammetry-service:batchAllowedZones:
    - southamerica-east1-a
    - southamerica-east1-b
  photogrammetry-service:batchMaxRunDuration: 43200s
  photogrammetry-service:batchMaxRetryCount: 2
  photogrammetry-service:batchProvisioningModel: STANDARD
  photogrammetry-service:batchMachineTiers:
    - maxImages: 200
      machineType: n2-standard-4
      cpuMilli: 4000
      memoryMib: 16384
    - maxImages: 500
      machineType: n2-standard-8
      cpuMilli: 8000
      memoryMib: 32768
    - maxImages: 1000
      machineType: n2-highmem-8
      cpuMilli: 8000
      memoryMib: 65536
    - maxImages: 2000
      machineType: n2-highmem-16
      cpuMilli: 16000
      memoryMib: 131072
    - maxImages: 99999
      machineType: n2-highmem-32
      cpuMilli: 32000
      memoryMib: 262144
  photogrammetry-service:batchMinBootDiskMb: 51200
  photogrammetry-service:batchDiskSafetyMargin: 1.15
  photogrammetry-service:batchAvgImageSizeMb: 9
  photogrammetry-service:batchWorkerCommand: "python3,/worker/main.py"
  photogrammetry-service:batchLogDestination: CLOUD_LOGGING
  photogrammetry-service:apiMinScale: 0
  photogrammetry-service:apiMaxScale: 10
  photogrammetry-service:cloudRunPublicAccess: true
  photogrammetry-service:enableOperationalAlerts: false
  photogrammetry-service:pubsubBacklogSubscriptions: []
