name: photogrammetry-service
description: Photogrammetry processing service infrastructure on GCP
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-typescript
